### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by zjyalice** [HumamAlwassel/action-search#1]
Hi~
I have some questions about action search.
Which framework do you use? tensorflow or pytorch?
And I only see the codes about action search sequence and figure generation, Do you like to open the source of train and test ? 

Best wishes !

**Comment by HumamAlwassel** [comment]
Thank you for your interest in our work. We implemented the training and testing code of Action Search in TensorFlow. Unfortunately, we don't plan to release the code.

Cheers
